[build]
  command = "gatsby build"
  functions = "netlify/functions"
  publish = "public"

## Edge Functions
[[edge_functions]]
  function = "proxy"
  path = "/api/proxy"

## Rewrite image URLs marked with imgcdn=true to use Netlify Image CDN
[[redirects]]
  from = "/*"
  query = {imgcdn = "true"}
  to = "/.netlify/images?url=/:splat&fm=webp"
  status = 200
  force = true
